### ISSUE TITLE
Are you know about cobrascript?

### ISSUE THREAD

**Issue by niwibe** [timothycrosley/jiphy#1]
https://github.com/niwibe/cobrascript

It has currently do the same thing, that your package, it works at ast level, translates AST -> AST
Let it a look! I'm currenly not maintaining it because it was a experiment, but if you found it useful I can give you the repository ;)

**Comment by timothycrosley** [comment]
Hi @niwibe!

No I hadn't heard of this project, but it looks like a very well done Python AST based approach and I will certainly look through it and try to pull anything out that is particularly applicable to Jiphy. 

Thanks!

~Timothy Crosley
