### ISSUE TITLE
For loop incorrect placement of closing bracket

### ISSUE THREAD

**Issue by Dimitri0xff** [timothycrosley/jiphy#14]
The following python code
```python
def clear():
    grid = []
    for i in range(0, config.SIZE):
        grid.append(0)
```
maps to
```javascript
function clear() {
    grid = [];
    for (i in range(0, config.SIZE)) {
        grid.push(0;    });
}
```
This happens with while loops as well. Do you know any workaround?

**Comment by timothycrosley** [comment]
Hi @Dimitri0xff,

Thanks for finding this issue! I've pushed a new release to PYPI `1.2.1` which is available for download now and resolves this problem.

Thanks!

~Timothy
